services:

  tienda-api-rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tienda-api-rest
    restart: always
    env_file: .env.prod
    ports:
      - ${PORT}:3000
    volumes:
      - storage-dir:/app/storage-dir
      - ./cert:/app/cert
    networks:
      - funkoshop-network

# Volume para guardar los datos de la base de datos
volumes:
  storage-dir:

networks:
  funkoshop-network:
    driver: bridge